# .NET Build & Publish NuGet
name: Build & Publish NuGet

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*' # release tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Set package version
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ "${GITHUB_REF_NAME}" == "master" ]]; then
            VERSION="1.0.0-beta.${GITHUB_RUN_NUMBER}"
          else
            VERSION="0.0.0-ci.${GITHUB_RUN_NUMBER}"
          fi
          echo "Version set to $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Pack XbrzSharp
        run: dotnet pack src/XbrzSharp/XbrzSharp.csproj -c Release -o ./artifacts /p:Version=$VERSION --no-build

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./artifacts/*.nupkg

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Download NuGet packages
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
